language: python

python:
  - 3.4.3
  - 3.5.0

services:
  - postgresql
  - memcached

env:
  - DJANGO=1.8.5
  - DJANGO=1.8.6

before_install:
  - export DJANGO_SETTINGS_MODULE=freds_list.travis-settings
  - export PYTHONPATH=$HOME/builds/cesarmarroquin/freds_list
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE fredslist3;" -U postgres
  - python manage.py migrate

script:
 - coverage run --source='.' manage.py test users fredslist api

after_success:
 - coveralls